### ISSUE TITLE
[FEAT] 게시판 CRUD

### ISSUE THREAD

**Issue by eunkangchoi** [5th-wanted-pre-onboarding-teamG/1_statistics#19]
- [x] [최영남] 게시판 등록  (#14) 
- [x] [강진희] 게시판 조회 (#34 )
- [x] [이성태] 게시판 상세페이지 (#31, #30 )
- [x] [최은강] 게시판 수정  (#7 )
- [x] [김용범] 게시판 삭제 (soft-delete) (#10 )

- 게시판 조회 (종류 상관X)
GET /boards

- 게시판 종류에 따른 조회
GET /boards?type=게시판종류

- 상세조회 
GET /boards/:boardId 

POST /boards?type=게시판 종류

PATCH /boards/:boardId

DELETE /boards/:boardId
